### ISSUE TITLE
Should the simple units tabel contain all values from IEEE 1541-2002?

### ISSUE THREAD

**Issue by bakugod** [tc39/proposal-intl-enumeration#15]
If your table contain bit and byte, could you add a kibibyte, mebibyte and other values from this [standart](https://standards.ieee.org/standard/1541-2002.html)?

**Comment by sffc** [comment]
This is blocked on supporting these units in 402 for formatting. There has been some movement on the CLDR side, and at this point we are waiting on the ICU implementation. Main issue: https://github.com/tc39/ecma402/issues/449
