### ISSUE TITLE
More things that we might enumerate over

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-intl-enumeration#2]
These are some things that I could imagine using in a picker
- Languages
- Regions

In general, if something is supported by Intl.DurationFormat, I wonder if you might want to be able to enumerate over supported values.

For example, this set includes scripts, but maybe enumerating over scripts is only useful in conjunction with data about which scripts may be meaningful for a given locale, which is a whole other project...

**Comment by sffc** [comment]
We have methods like `Intl.NumberFormat.supportedLocalesOf()`, although that's returning an empty array for me on Chrome 80.

More generally, deciding what is "supported" is an inexact science.  For languages, does "supported" mean that you have a nonempty locale data file?  For regions, how do you define what "supported" means in that case?  That you have a display name for it?

**Comment by littledan** [comment]
`supportedLocalesOf` takes a larger set of locales that you are asking for a subset of. I guess what I'm suggesting that we make an API which gives the supported locales of the universal set.

Yes, this is definitely inexact. I'd suggest that this API be broad in general, erring on the side of including more things (e.g., having the display name), and then we can let programmers use more fine-grained APIs if they want to test support for a particular API (e.g., `supportedLocalesOf` or `resolvedOptions`).

(Hmm, maybe this means we would actually want Temporal.TimeZone to have  way to check support for timezones/iterate through all the actually supported ones...)

**Comment by littledan** [comment]
Or, on second thought: Maybe things like language/region enumeration should be part of `Intl.DisplayNames`, and the iteration functions on `Intl` is more about options supported across APIs.

**Comment by FrankYFTang** [comment]
This proposal is in Stage 3 now. Close the issue down
