### ISSUE TITLE
List Locales

### ISSUE THREAD

**Issue by Lonniebiz** [tc39/proposal-intl-enumeration#41]
Does this proposal offer a way to list locales as well?
https://stackoverflow.com/questions/52549577/javascript-get-the-complete-list-of-locales-supported-by-the-browser

**Comment by FrankYFTang** [comment]
No, this proposel does NOT offer a way to list locales. The reason is the permutation of all possible locales are way too long.

**Comment by Lonniebiz** [comment]
That's what she said (to me)!

**Comment by ljharb** [comment]
@Lonniebiz that comment is highly inappropriate and does not comply with our code of conduct. I’ll hide it now, as well as this comment.
